# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be3f1696a51a4092087b0219d0f2de3cee88a50ff914b6547b9ce1d49a3dbacca3dac92dc23901d469d9a8e6963ccb6efb19e74ef0010f0ccd5fe99c154e108e

test:
  secret_key_base: 8066c6b244565538cba31fdbe26977bb297c74c283b9930c4a116baa20deff205db9791bbb9e9350a46aec51570bc92bc5ecdd5fe129256b81839df983c0c84a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
